version: "3"

services:
        tgdb:
                build: ./mysql
                container_name: tgdb
                ports:
                        - "3306:3306"
                volumes:
                        - ./mysql/data:/var/lib/mysql

        tgweb:
                build: ./UC
                container_name: tgweb
                ports:
                        - "8000:8000"
                depends_on:
                        - tgdb
               

        tgtraffic:
                build: ./nginx
                container_name: tgtraffic
                ports:
                        - "5005:5005"
                depends_on:
                        - tgweb

        tgclusterdebugger:
                build: ./debugger
                container_name: tgclusterdebugger
                ports:
                        - "6700:6700"



